### PR TITLE
Zorginzage-transactions

### PR DESCRIPTION
**Pull request by bramwesselo**

### CODE REVIEW

**Comment by jorritspee** [comment]
"Cedric's GP/Hospital-data is now showing up instantly in the, e.g., conditions, measurements and events sections of the dossier. " is quite a complex sentence
Proposal: 
"Cedric's GP/Hospital-data is now showing up instantly in the appropriate sections of the dossier."

**Comment by jorritspee** [comment]
10.1.1 step 1:
"The data endpoints of the care providers (GP & hospital) are looked up in the local provider directory"
I think it is not the "data endpoint" but more a "workflow endpoint"?
I thought you just wanted to send a Task to the GP "do you want to preform GP-care?" but the text in step 2 suggests that you want to use a slightly different mechanism.

**Comment by jorritspee** [comment]
10.1.1 "home care nurse"
Ik zou "Community nurse" gebruiken, dat is snomed code "224540001", "wijkverpleegkundige".

**Comment by jorritspee** [comment]
Titel "Use cases - Get data for home monitoring"
moet zijn "Use cases - Get data for home care"

**Comment by bramwesselo** [comment]
> 10.1.1 step 1: "The data endpoints of the care providers (GP & hospital) are looked up in the local provider directory" I think it is not the "data endpoint" but more a "workflow endpoint"? I thought you just wanted to send a Task to the GP "do you want to preform GP-care?" but the text in step 2 suggests that you want to use a slightly different mechanism.

Changed 'data endpoint' to 'service endpoint'
Added the code-challenge for Cedric's consent. Not sure what you mean by the 'slightly different mechanism'. Is it okay now?

**Comment by jorritspee** [comment]
Lookin good now! Really love the code challenge flow! <3

**Pull request merged**
